name: Build IPQ6K EMMC

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  #手动编译
  workflow_dispatch:

jobs:
  modify-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Modify QCA-ALL to QCA-EMMC
      run: |
        # 生成临时文件
        cp .github/workflows/QCA-ALL.yml .github/workflows/QCA-EMMC.yml

        # 修改名称
        sed -i 's/name: QCA-ALL/name: QCA-EMMC/' .github/workflows/QCA-EMMC.yml
        
        # 修改TARGET值
        sed -i 's/TARGET: \[IPQ60XX-WIFI-YES, IPQ60XX-WIFI-NO, IPQ807X-WIFI-YES, IPQ807X-WIFI-NO\]/TARGET: \[IPQ60XX-EMMC-WIFI-YES, IPQ60XX-EMMC-WIFI-NO\]/' .github/workflows/QCA-EMMC.yml
        
    - name: Print modified workflow
      run: |
        echo "==== Modified Workflow ===="
        cat .github/workflows/QCA-EMMC.yml

    - name: Commit and push QCA-EMMC.yml
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
        git add .github/workflows/QCA-EMMC.yml
        git commit -m "Add QCA-EMMC workflow for temporary use"
        git push origin ${{ github.ref_name }}
      
    - name: Trigger modified workflow
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: "QCA-EMMC.yml",
            ref: context.ref
          })
