name: Sync YML Files

on:
  push:
    paths:
      - '.github/workflows/QCA-ALL.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:
  contents: write

  
jobs:
  sync-qca-files:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 同步并修改文件内容
      - name: Sync and Modify QCA Config
        run: |
          # 读取 QCA-ALL.yml 的内容
          sed 's/name: QCA-ALL/name: QCA-EMMC/' .github/workflows/QCA-ALL.yml | \
          sed 's/TARGET: \[IPQ60XX-WIFI-YES, IPQ60XX-WIFI-NO, IPQ807X-WIFI-YES, IPQ807X-WIFI-NO\]/TARGET: [IPQ60XX-EMMC-WIFI-YES, IPQ60XX-EMMC-WIFI-NO]/' > .github/workflows/QCA-EMMC.yml

      # 提交更改
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .github/workflows/QCA-EMMC.yml
          git commit -m "Sync QCA-ALL.yml to QCA-EMMC.yml with modifications"
          git push
